version: "3.9"
services:
  api:
    container_name: blueprint-nodejs-docker
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      POSTGRES_DB_HOST: blueprint-nodejs-docker-postgres-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
      RABBITMQ_HOST: blueprint-nodejs-docker-rabbitmq-broker
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASSWORD: foobar
      FOLDER: /tmp
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp