version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: blueprint-nodejs-docker-postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      - blueprint-nodejs-docker-net
    volumes:
      - ${PWD}/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  broker:
    image: rabbitmq:4.0-management-alpine
    container_name: blueprint-nodejs-docker-rabbitmq-broker
    hostname: blueprint-nodejs-docker-rabbitmq-broker
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: foobar
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${PWD}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ${PWD}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - blueprint-nodejs-docker-net

  api:
    container_name: blueprint-nodejs-docker
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      POSTGRES_DB_HOST: blueprint-nodejs-docker-postgres-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
      RABBITMQ_HOST: blueprint-nodejs-docker-rabbitmq-broker
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: foobar
      FOLDER: /tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
      - broker
    networks:
      - blueprint-nodejs-docker-net
    volumes:
      - /tmp:/tmp

networks:
  blueprint-nodejs-docker-net:
    driver: bridge
